services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=abrish
      - POSTGRES_PASSWORD=abrish
      - POSTGRES_DB=cms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U abrish -d cms_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=abrhambest7@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=abrish
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://abrish:abrish@db:5432/cms_db?schema=public
      - BETTER_AUTH_SECRET=your-super-secret-key-change-this-in-production-min-32-chars
      - BETTER_AUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - UPLOAD_DIR=/app/public/uploads
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/public/uploads

volumes:
  postgres_data:
  uploads_data:
